name: Publish to Maven Central

on:
  release:
    types: [released]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    if: github
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Build with Gradle
        # This just publishes to the local file system; jreleaser is responsible for uploading to maven central
        run: ./gradlew publish
      - name: Upload to Maven Central
        env:
          # Needs to have access to the io.github.ArchipelagoMW namespace in maven central
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.mavenCentralUsername }}
          JRELEASER_MAVENCENTRAL_TOKEN: ${{ secrets.mavenCentralToken }}
#          JRELEASER_DEPLOY_MAVEN_NEXUS2_USERNAME: ${{ secrets.mavenCentralUsername }}
#          JRELEASER_DEPLOY_MAVEN_NEXUS2_TOKEN: ${{ secrets.mavenCentralToken }}
          # The content uploaded to maven central needs to be signed.  The public keys need to be published,
          # see https://central.sonatype.org/publish/requirements/gpg/#distributing-your-public-key for accepted
          # locations
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.gpgPassphrase }}
          # The content here needs to be the values of the public and secret key pair
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.gpgPublicKey }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.gpgSecretKey }}
        run: gradlew jreleaserDeploy